### ISSUE TITLE
绑定合作站点时 ssl 错误

### ISSUE THREAD

**Issue by yegetables** [ledccn/iyuuplus-dev#102]
![image](https://github.com/user-attachments/assets/b71f3113-5054-422e-ac79-9417401117cf)
站点: icc2022

docker-compose
```yaml
ajian@fnos:/vol1/1000/docker/iyuuplus-dev$ cat docker-compose.yml
version: '3.8'
services:
  iyuuplus:
    stdin_open: true
    tty: true

    image: iyuucn/iyuuplus-dev:latest
    container_name: iyuuplus-dev
    restart: always
    volumes:
      - ./iyuu:/iyuu
      - ./data:/data
      - /vol1/1000/docker/qb-offical/config/qBittorrent/BT_backup:/qb
    ports:
      - "38787:8780"
    network_mode: bridge
```
