### ISSUE TITLE
只要重启docker就报错，这代码写的。。。

### ISSUE THREAD

**Issue by Lizhen0628** [ledccn/iyuuplus-dev#67]
Next Illuminate\Database\QueryException: SQLSTATE[HY000] [2002] No such file or directory (Connection: plugin.admin.mysql, SQL: select * from `cn_crontab` where `enabled` = 1 order by `sort` desc) in /iyuu/vendor/illuminate/database/Connection.php:829

**Comment by ledccn** [comment]
数据库丢失了；检查是否挂载/data

**Comment by Sartner** [comment]
确实有问题，使用docker restart之后就无法启动了。

docker-compose
``` 
version: "3"
services:
  iyuu:
    stdin_open: true
    tty: true
    volumes:
      - /share/Container/iyuu/iyuu:/iyuu
      - /share/Container/iyuu/data:/data
    ports:
      - "8780:8780"
    container_name: iyuu
    restart: always
    image: iyuucn/iyuuplus-dev:latest
```

启动之后直接 docker restart iyuu 就寄了
